name: release

on:
   push:
    branches:
      - main
    tags:
      - "Version:*"
   workflow_dispatch: 
  
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: christophebedard/tag-version-commit@v1
      with:
        token: ${{ secrets.TOKEN }}
        version_regex: 'Version: ([0-9]+\.[0-9]+\.[0-9]+)'
        version_tag_prefix: 'prod-v'
